### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by LuckyJack101** [sam3d/vue-svg#10]
Hi there,

I have been using  your plugin on my Vue 2 projects and would really like to use on my new Vue 3 project as well, but it's not you applicable.

**Setup**
I did a `vue create my-app` and selected vue 3.x using `@vue/cli 4.5.9`.

**Issue**
When doing the **vue add svg** it installs but gives `Plugin vue-cli-plugin-svg does not have a generator to invoke` as a message in the terminal.
When running `npm run serve` it tells me `Cannot find module 'vue-template-compiler`. This seems to be because vue-cli is now using `@vue/compiler-sfc` instead of `vue-template-compiler`.

Best regards

**Comment by FedorSherbakov** [comment]
@LuckyJack101 you can check [my PR](https://github.com/sam3d/vue-svg/pull/11)
I was mostly interested in inline svg, so didn't test other options yet, but inline works!

You can install it like that: `npm install -D git+https://github.com/FedorSherbakov/vue-svg.git`

**Comment by Wambosa** [comment]
Confirmed that @FedorSherbakov's solution works. Just used his branch and can move forward with vue3.
Thank you for figuring that out man!

**Comment by reslear** [comment]
> @LuckyJack101 you can check [my PR](https://github.com/sam3d/vue-svg/pull/11)

fork on npm https://www.npmjs.com/package/vue-cli-plugin-svg-vue3

if use ionic need vscode search: `from './../assets/images` and replace to `from '@/assets/images`

**Comment by sam3d** [comment]
Released in v0.2.0 🎉
